kind: Deployment
apiVersion: apps/v1
metadata:
  name: ms-hello-world
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-hello-world
  template:
    metadata:
      labels:
        app: ms-hello-world
    spec:
      containers:
      - name: ms-hello-world
        image: jnode:18-alpine
        ports:
        - containerPort: 8081

