apiVersion: v1
kind: Service
metadata:
  name: ms-hello-world
  labels:
    app: ms-hello-world
spec:
  type: LoadBalancer
  ports:
  - port: 8081
    targetPort: 8081
  selector:
    app: ms-hello-world

